backend:
  name: git-gateway
  branch: master

media_folder: "static"
public_folder: "/images"
publish_mode: editorial_workflow

collections:

  - name: "experts"
    label: "Эксперты"
    label_singular: "Эксперт"
    folder: "content/experts"
    slug: "{{fields.slug}}"
    path: "{{slug}}/_index"
    media_folder: "../../../static/images/experts"
    public_folder: "/images/experts"
    create: true
    fields:

      - label: "Фамилия"
        name: "lastName"
        widget: "string"
        required: true

      - label: "Имя"
        name: "firstName"
        widget: "string"
        required: true

      - label: "Slug"
        name: "slug"
        widget: "string"
        required: true

      - label: "Описание"
        name: "description"
        widget: "string"
        required: true

      - label: "Иллюстрация"
        name: "image"
        widget: "image"
        required: true

      - label: "Заголовок"
        name: "title"
        widget: "string"
        required: false

  - name: "comments"
    label: "Комментарии"
    label_singular: "Комментарий"
    folder: "content/comments"
    create: true
    slug: "{{fields.id}}"
    fields:
      - label: "ID"
        name: "id"
        widget: "ncw-id"
        required: true

      - label: "Заголовок"
        name: "title"
        widget: "string"
        required: true

      - label: "Дата публикции"
        name: "date"
        widget: "datetime"
        required: true

      - label: "YouTube"
        name: "youtube"
        widget: "string"
        required: true

      - label: "Эксперты"
        name: "experts"
        widget: "relation"
        collection: "experts"
        searchFields: ["lastName"]
        valueField: "slug"
        displayFields: ["lastName"]
        multiple: true
        required: true

      - label: "Лид"
        name: "lead"
        widget: "markdown"
        required: true

      - label: "Текст"
        name: "body"
        widget: "markdown"
        required: false

  - name: "categories"
    label: "Категории"
    label_singular: "Категория"
    folder: "content/categories"
    slug: "{{fields.slug}}"
    path: "{{slug}}/_index"
    create: true
    fields:
      - label: "Название"
        name: "name"
        widget: "string"
        required: true

      - label: "Slug"
        name: "slug"
        widget: "string"
        required: true

  - name: "sources"
    label: "Источники"
    label_singular: "Источник"
    folder: "content/sources"
    slug: "{{fields.slug}}"
    path: "{{slug}}/_index"
    create: true
    fields:
      - label: "Название"
        name: "name"
        widget: "string"
        required: true

      - label: "Slug"
        name: "slug"
        widget: "string"
        required: true

  - name: "news"
    label: "Новости"
    label_singular: Новость
    folder: "content/news"
    create: true
    slug: "{{fields.id}}"
    media_folder: "../../static/images/news"
    public_folder: "/images/news"
    fields:
      - label: "ID"
        name: "id"
        widget: "ncw-id"
        required: true

      - label: "Заголовок"
        name: "title"
        widget: "string"
        required: true

      - label: "Источник"
        name: "sources"
        widget: "relation"
        collection: "sources"
        searchFields: ["name"]
        valueField: "slug"
        displayFields: ["name"]
        required: true

      - label: "Ссылка"
        name: "link"
        widget: "string"
        required: true

      - label: "Дата публикации"
        name: "date"
        widget: "datetime"
        required: true

      - label: "Комментарии"
        name: "comments"
        widget: "relation"
        collection: "comments"
        searchFields: ["title"]
        valueField: "id"
        displayFields: ["title"]
        multiple: true
        required: false

      - label: "Иллюстрация"
        name: "image"
        widget: "image"
        required: false

      - label: "Категории"
        name: "categories"
        widget: "relation"
        collection: "categories"
        searchFields: ["name"]
        valueField: "slug"
        displayFields: ["name"]
        required: true

      - label: "Лид"
        name: "lead"
        widget: "markdown"
        required: true

      - label: "Текст"
        name: "body"
        widget: "markdown"
        required: false
