backend:
  name: git-gateway
  branch: master

media_folder: "static"
public_folder: "/images"
publish_mode: editorial_workflow

collections:
  - name: "news"
    label: "Новости"
    label_singular: Новость
    folder: "content/news"
    create: true
    slug: "{{fields.id}}"
    media_folder: "../../static/images/news"
    public_folder: "/images/news"
    fields:
      - label: "ID"
        name: "id"
        widget: "ncw-id"
        required: true

      - label: "Заголовок"
        name: "title"
        widget: "string"
        required: true

      - label: "Источник"
        name: "sources"
        widget: "relation"
        collection: "sources"
        searchFields: ["name"]
        valueField: "slug"
        displayFields: ["name"]
        required: true

      - label: "Ссылка"
        name: "link"
        widget: "string"
        required: true

      - label: "Дата публикации"
        name: "date"
        widget: "datetime"
        required: true

      - label: "Комментарии"
        name: "comments"
        widget: "relation"
        collection: "comments"
        searchFields: ["title"]
        valueField: "id"
        displayFields: ["title"]
        multiple: true
        required: false

      - label: "Иллюстрация"
        name: "image"
        widget: "image"
        required: false

      - label: "Текст"
        name: "body"
        widget: "markdown"
        required: false

  - name: "comments"
    label: "Comments"
    label_singular: Comment
    folder: "content/comments"
    create: true
    slug: "{{fields.id}}"
    fields:
      - label: "ID"
        name: "id"
        widget: "ncw-id"
        required: true

      - label: "Title"
        name: "title"
        widget: "string"
        required: true

      - label: "Publish Date"
        name: "date"
        widget: "datetime"
        required: true

      - label: "YouTube"
        name: "youtube"
        widget: "string"
        required: true

      - label: "Experts"
        name: "experts"
        widget: "relation"
        collection: "experts"
        searchFields: ["lastName"]
        valueField: "slug"
        displayFields: ["lastName"]
        multiple: true
        required: true

      - label: "Body"
        name: "body"
        widget: "markdown"
        required: false

  - name: "experts"
    label: "Experts"
    label_singular: "Expert"
    folder: "content/experts"
    slug: "{{fields.slug}}"
    path: "{{slug}}/_index"
    media_folder: "../../../static/images/experts"
    public_folder: "/images/experts"
    create: true
    fields:
      - label: "Last Name"
        name: "lastName"
        widget: "string"
        required: false

      - label: "First Name"
        name: "firstName"
        widget: "string"
        required: false

      - label: "Slug"
        name: "slug"
        widget: "string"
        required: false

      - label: "Description"
        name: "description"
        widget: "string"
        required: false

      - label: "Image"
        name: "image"
        widget: "image"
        required: false

  - name: sources
    label: Sources
    label_singular: 'source'
    folder: content/sources
    slug: "{{fields.slug}}"
    path: '{{slug}}/_index'
    create: true
    fields:
      - label: Name
        name: name
        widget: string
      - label: Slug
        name: slug
        widget: string
